services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAZI2LB7FLWIR7QH4K
      - AWS_SECRET_ACCESS_KEY=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

